# Generated by Django 6.0.2 on 2026-04-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='page_count',
            field=models.IntegerField(blank=True, help_text='Auto-extracted from manuscript', null=True),
        ),
    ]
