# Generated by Django 6.0.2 on 2026-04-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_submission_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
